Repository metallb/metallb, pull requests merged in 2020-06, with the labels that each got.

#640 Fix the README "widgets"
  README.md
Labels: documentation

#600 expand install docs how to easily automate strictARP change
  website/content/installation/_index.md
Labels: documentation

#642 website: Add #metallb-dev slack channel
  website/content/community/_index.md
Labels: documentation

#641 tasks.py: Drop unused imports
  tasks.py
Labels: cleanup

#638 ci: Split lint out into its own job
  .circleci/config.yml
Labels: testing
