Repository metallb/metallb, pull requests merged in 2020-08, with the labels that each got.

#678 bgp: Decode hold timer expired notification
  internal/bgp/messages.go
Labels: protocol/BGP

#661 Document maintainership of MetalLB
  CODEOWNERS
  website/content/community/_index.md
  website/content/community/maintainers.md
Labels: documentation, process

#690 Website: Add upgrade information
  website/content/installation/_index.md
Labels: documentation

#659 Publish images for each open pull request
  .circleci/config.yml
  website/content/community/_index.md
Labels: testing

#671 Add a note to the website about single-IP address pool
  website/content/configuration/_index.md
Labels: documentation
