Repository metallb/metallb, pull requests merged in 2021-06, with the labels that each got.

#859 design: Propose a MetalLB operator
  design/metallb-operator.md
Labels: design-proposal

#860 Propose that MetalLB apply to the CNCF Sandbox
  design/cncf-sandbox-proposal.md
Labels: design-proposal

#876 release: Fix image reference regex
  tasks.py
Labels: bug

#870 e2etest: Display error message when testing unconfigured dev-env
  tasks.py
Labels: cleanup

#892 Add wget retries to both layer2 and bgp e2e tests
  e2etest/bgp_test.go
  e2etest/layer2_test.go
  e2etest/utils.go
Labels: ci, testing

#893 charts: Clear version in Chart.yaml in main branch
  charts/metallb/Chart.yaml
Labels: helm
