Repository metallb/metallb, pull requests merged in 2024-09, with the labels that each got.

#2497 bump kind version and utilities
  tasks.py
Labels: kind/cleanup

#2501 Fix typos
  charts/metallb/values.yaml
Labels: kind/cleanup

#2515 chore: update toolchain to go 1.22.7
  configmaptocrs/Dockerfile
  controller/Dockerfile
  e2etest/go.mod
  e2etest/go.work
  e2etest/go.work.sum
  go.mod
  speaker/Dockerfile
Labels: kind/cleanup

#2528 Safeconvert: add arm specific code for int to uint32
  internal/safeconvert/convert.go
  internal/safeconvert/convertuint32.go
  internal/safeconvert/convertuint32_arm.go
Labels: kind/cleanup

#2524 Lint tasks.py
  .github/workflows/ci.yaml
  .github/workflows/composite/setup/action.yaml
  .github/workflows/publish.yaml
  dev-env/requirements.txt
  tasks.py
  website/content/community/_index.md
Labels: kind/cleanup

#2529 Use the official govulncheck gh action
  .github/workflows/ci.yaml
  .github/workflows/vulncheck_periodic.yaml
Labels: kind/cleanup

#2517 dev-env: Add missing parts to support dual stack
  dev-env/bgp/config.yaml.j2
  dev-env/bgp/frr/bgpd.conf.j2
  tasks.py
Labels: kind/bug

#2536 E2E: ignore stderr if error is nil when kubectl exec
  e2etest/pkg/executor/executor.go
Labels: kind/flake

#2539 Bump frr-k8s, k8s deps, dependabot deps
  charts/metallb/Chart.lock
  charts/metallb/Chart.yaml
  charts/metallb/README.md
  charts/metallb/charts/crds/templates/crds.yaml
  charts/metallb/charts/frr-k8s-0.0.14.tgz
  charts/metallb/charts/frr-k8s-0.0.15.tgz
  config/crd/bases/metallb.io_bfdprofiles.yaml
  config/crd/bases/metallb.io_bgpadvertisements.yaml
  config/crd/bases/metallb.io_bgppeers.yaml
  config/crd/bases/metallb.io_communities.yaml
  config/crd/bases/metallb.io_ipaddresspools.yaml
  config/crd/bases/metallb.io_l2advertisements.yaml
  config/crd/bases/metallb.io_servicel2statuses.yaml
  config/frr-k8s/kustomization.yaml
  config/manifests/metallb-frr-k8s-prometheus.yaml
  config/manifests/metallb-frr-k8s.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
  config/manifests/metallb-native-prometheus.yaml
  config/manifests/metallb-native.yaml
  config/prometheus-frr-k8s/kustomization.yaml
  e2etest/go.mod
  e2etest/go.sum
  e2etest/go.work.sum
  go.mod
  go.sum
  tasks.py
Labels: kind/cleanup

#2518 Manifests: Add speaker delete FRRConfiguration rbac
  charts/metallb/templates/rbac.yaml
  config/frr-k8s-external/clusterrole-patch.yaml
  config/frr-k8s/clusterrole-patch.yaml
  config/manifests/metallb-frr-k8s-prometheus.yaml
  config/manifests/metallb-frr-k8s.yaml
  config/prometheus-frr-k8s/clusterrole-patch.yaml
Labels: kind/bug
