Repository metallb/metallb, pull requests merged in 2024-12, with the labels that each got.

#2624 Fix(tests): resolve flakiness in service pool reassignment test
  e2etest/l2tests/assignment.go
Labels: kind/flake

#2588 Website: mention RPF in the metallb troubleshooting guide
  website/content/troubleshooting/_index.md
Labels: kind/documentation

#2567 tasks: use local ginkgo
  tasks.py
Labels: kind/cleanup

#2590 Docs: document the vrf label in bgp related metrics
  website/content/prometheus-metrics/_index.md
Labels: kind/documentation

#2591 Move russell and graeme to emeritus maintainers
  CODEOWNERS
  README.md
Labels: lifecycle-stale, kind/cleanup

#2592 Website: set redirects for metallb.universe.tf to metallb.io
  netlify.toml
Labels: kind/cleanup

#2594 Docs: document the ip reconciliation behavior
  website/content/concepts/_index.md
Labels: kind/documentation

#2620 CI: Re-enable L2ServiceStatus e2es
  .github/workflows/ci.yaml
Labels: kind/cleanup

#2621 :book: Add documentation for the newly added support of `PreferDualStack` in…
  website/content/configuration/_advanced_ipaddresspool_configuration.md
Labels: kind/documentation

#2593 IPV6 bgp validation: validate bgpadvertisement selected pools
  internal/config/validation.go
  internal/config/validation_test.go
Labels: lifecycle-stale, kind/bug
