Repository metallb/metallb, pull requests merged in 2024-10, with the labels that each got.

#2495 Service annotations: change annotation prefix to metallb.io
  controller/main.go
  controller/service.go
  e2etest/bgptests/bgp.go
  e2etest/l2tests/l2.go
  e2etest/pkg/service/tweak.go
  e2etest/pkg/service/validate.go
  internal/allocator/k8salloc/k8salloc.go
Labels: kind/feature

#2513 Added spaces for mermaid diagram subgraph titles to fix syntax error
  website/content/configuration/_advanced_bgp_configuration.md
  website/content/configuration/calico.md
Labels: kind/documentation

#2527 Publish jobs: bump gh actions
  .github/workflows/publish.yaml
Labels: kind/cleanup

#2538 Add log for L2 speaker when node is not usable
  speaker/layer2_controller.go
Labels: kind/cleanup

#2523 apply Prometheus best practices to existing alerts
  charts/metallb/README.md
  charts/metallb/templates/prometheusrules.yaml
  charts/metallb/values.yaml
Labels: kind/cleanup

#2508 Unnumbered BGP Peering design document
  design/unnumbered-bgp.md
Labels: kind/design

#2570 E2E: increase debugging for the external peers
  e2etest/pkg/frr/config/config.go
Labels: kind/flake
