Repository metallb/metallb, pull requests merged in 2024-06, with the labels that each got.

#2390 Added speaker monitor service labels
  charts/metallb/templates/servicemonitor.yaml
Labels: kind/bug

#2407 Minor spelling fix for bgp.md
  website/content/concepts/bgp.md
Labels: kind/documentation

#2417 Use ginkgo version specified in go.mod
  .github/workflows/composite/setup/action.yaml
Labels: kind/cleanup

#2418 Use distroless image to build controller and speaker containers
  charts/metallb/templates/speaker.yaml
  config/frr/speaker-patch.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
  configmaptocrs/Dockerfile
  controller/Dockerfile
  e2etest/l2tests/interface_selector.go
  e2etest/pkg/executor/executor.go
  frr-tools/cp-tool/cp-tool.go
  speaker/Dockerfile
  website/content/troubleshooting/_index.md
Labels: kind/feature

#2420 Charts: don't log history in liveness probe
  charts/metallb/templates/speaker.yaml
  config/frr/speaker-patch.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
Labels: kind/bug
