Repository metallb/metallb, pull requests merged in 2024-04, with the labels that each got.

#2346 Use docker buildx version instead of ls for buildx check.
  tasks.py
Labels: kind/cleanup

#2356 CI: don't run the labeler job on dependabot prs
  .github/workflows/classify.yaml
Labels: kind/cleanup

#2361 chore: fix function names in comment
  e2etest/pkg/frr/bgp.go
  internal/bgp/frr/config.go
  internal/k8s/webhooks/webhookv1beta1/l2advertisement_webhook.go
Labels: kind/documentation

#2363 chore: update go to 1.21.9
  configmaptocrs/Dockerfile
  controller/Dockerfile
  speaker/Dockerfile
Labels: kind/cleanup

#2337 Fix the handling of readyness conditions of endpointslices
  internal/k8s/epslices/endpoint_slices.go
  internal/k8s/epslices/endpoint_slices_test.go
  speaker/bgp_controller.go
  speaker/bgp_controller_test.go
  speaker/layer2_controller.go
  speaker/layer2_controller_test.go
Labels: kind/bug

#2349 inv dev-env fails with --protocol=layer2 because ip address error
  tasks.py
Labels: kind/bug

#2384 Improve error message when keepalivetime is invalid
  internal/config/config.go
  internal/config/config_test.go
Labels: kind/cleanup
