Repository metallb/metallb, pull requests merged in 2025-03, with the labels that each got.

#2716 fix: webhook to handle interface field of BGPPeer resource
  internal/config/validation.go
  internal/config/validation_test.go
Labels: kind/bug

#2647 feat(oci): publish chart to quay registry
  .github/workflows/publish.yaml
Labels: kind/feature

#2725 FRR mode: put a limit to the number of open file descriptors
  charts/metallb/templates/speaker.yaml
  config/frr/frr-cm.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
Labels: kind/bug

#2726 IP Assignement: match clusterip family in case of single stack clusterip
  controller/controller_test.go
  controller/service.go
  internal/allocator/allocation.go
Labels: kind/bug

#2732 Add an official adopters list
  ADOPTERS.md
Labels: kind/cleanup
