Repository metallb/metallb, pull requests merged in 2025-02, with the labels that each got.

#2684 Use latest 1.22 go
  configmaptocrs/Dockerfile
  controller/Dockerfile
  e2etest/go.mod
  e2etest/go.work
  go.mod
  speaker/Dockerfile
Labels: kind/cleanup

#2585 #364: Reject service IPs overlap with node IPs
  e2etest/webhookstests/webhooks.go
  internal/config/config.go
  internal/k8s/nodes/nodes.go
  internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook.go
  internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook_test.go
Labels: kind/bug

#2681 build: Fetch kubectl only if it is not present
  tasks.py
Labels: kind/bug

#2680 build: Install yq, required to generate manifests
  tasks.py
Labels: kind/bug

#2696 fix: Remove caBundle fields from webhook configurations
  charts/metallb/charts/crds/templates/crds.yaml
  config/crd/patches/crd-conversion-patch-bgppeers.yaml
  config/manifests/metallb-frr-k8s-prometheus.yaml
  config/manifests/metallb-frr-k8s.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
  config/manifests/metallb-native-prometheus.yaml
  config/manifests/metallb-native.yaml
Labels: kind/bug

#2691 Add redirect for the metallb.io/metallb vanity url
  website/content/metallb.md
  website/layouts/_default/vanityurl.html
Labels: kind/cleanup

#2694 Docs: specify the service account to use on OCP / helm
  website/content/installation/clouds.md
Labels: kind/documentation
